FROM openjdk:11 //it tells from where to obtain dependencies
EXPOSE 80 //exposing port 
WORKDIR /app //setting working directory
COPY . /app //copying content from local machine to that directory
CMD["java","jar","index.jsp"] //executing
